/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ISAS
 */
public class PengajuView extends javax.swing.JFrame {

    /**
     * Creates new form PengajuHomeView
     */
    public PengajuView() {
        initComponents();
        this.setSize(600, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnPengajuanBarang = new javax.swing.JButton();
        btnPengajuanMutasi = new javax.swing.JButton();
        btnDropPengajuan = new javax.swing.JButton();
        btnViewPengajuan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNotif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setLayout(new java.awt.CardLayout());

        btnPengajuanBarang.setText("Pengajuan Barang");

        btnPengajuanMutasi.setText("Pengajuan Mutasi");

        btnDropPengajuan.setText("Drop Pengajuan");

        btnViewPengajuan.setText("View Pengajuan");

        btnLogout.setText("Logout");

        btnNotif.setText("Notifikasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPengajuanBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPengajuanMutasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDropPengajuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPengajuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnNotif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnNotif))
                .addGap(22, 22, 22)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(btnPengajuanBarang)
                .addGap(18, 18, 18)
                .addComponent(btnPengajuanMutasi)
                .addGap(18, 18, 18)
                .addComponent(btnDropPengajuan)
                .addGap(18, 18, 18)
                .addComponent(btnViewPengajuan)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getBtnDropPengajuan() {
        return btnDropPengajuan;
    }

    public JButton getBtnPengajuanBarang() {
        return btnPengajuanBarang;
    }

    public JButton getBtnPengajuanMutasi() {
        return btnPengajuanMutasi;
    }

    public JButton getBtnViewPengajuan() {
        return btnViewPengajuan;
    }

    public JPanel getContent() {
        return content;
    }
    
    public CardLayout getCardLayout(){
        return (CardLayout) content.getLayout();
    }        
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDropPengajuan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotif;
    private javax.swing.JButton btnPengajuanBarang;
    private javax.swing.JButton btnPengajuanMutasi;
    private javax.swing.JButton btnViewPengajuan;
    private javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
}
